# main.yml
- name: Nginx AMI Build
  hosts: all
  become: true
  gather_facts: true

  pre_tasks:

    - name: upgrade all packages
      apt:
        update_cache: true
        upgrade: true

    - name: update all packages
      apt:
        name: "*"
        state: latest

  tasks:
    - name: Install and configure nginx
      include_tasks: ./tasks/nginx.yml
    
    - name: Install and configure ssm
      include_tasks: ./tasks/ssm.yml
    
    # As a security man, I do
    # highly recommended - https://github.com/dev-sec/ansible-collection-hardening
    - name: Install and configure ufw
      include_tasks: ./tasks/ufw.yml

